version = 5.4.0
archive_dir = /etc/letsencrypt/archive/mealaton.com
cert = /etc/letsencrypt/live/mealaton.com/cert.pem
privkey = /etc/letsencrypt/live/mealaton.com/privkey.pem
chain = /etc/letsencrypt/live/mealaton.com/chain.pem
fullchain = /etc/letsencrypt/live/mealaton.com/fullchain.pem
[renewalparams]
account = f6f67dc824432946abf34b1138f38f06
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
mealaton.com = /var/www/certbot
www.mealaton.com = /var/www/certbot
